/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_mobilepg_crypto_NativeAES */

#ifndef _Included_com_mobilepg_crypto_NativeAES
#define _Included_com_mobilepg_crypto_NativeAES
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_mobilepg_crypto_NativeAES
 * Method:    createInstance
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_mobilepg_crypto_NativeAES_createInstance
  (JNIEnv *, jobject);

/*
 * Class:     com_mobilepg_crypto_NativeAES
 * Method:    setupEncryptKey
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mobilepg_crypto_NativeAES_setupEncryptKey
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_mobilepg_crypto_NativeAES
 * Method:    encryptBuffer
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_mobilepg_crypto_NativeAES_encryptBuffer
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_mobilepg_crypto_NativeAES
 * Method:    setupDecryptKey
 * Signature: ([B)Z
 */
JNIEXPORT jboolean JNICALL Java_com_mobilepg_crypto_NativeAES_setupDecryptKey
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_mobilepg_crypto_NativeAES
 * Method:    decryptBuffer
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_mobilepg_crypto_NativeAES_decryptBuffer
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     com_mobilepg_crypto_NativeAES
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_mobilepg_crypto_NativeAES_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
